### ISSUE TITLE
`Bug`: couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

### ISSUE THREAD

**Issue by lgzcoollg** [gyptazy/ProxLB#103]
## General
apt-get install ./proxlb_1.0.4_amd64.deb
N: Download is performed unsandboxed as root as file '/root/proxlb_1.0.4_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

cli run user: root@pve1

## Weighting
Score: 9

## Config
no to that step

## Log
<-- Attach the ProxLB debug log for further analysis. Please take car to NOT publish your API credentials! -->

## Meta
Please provide some more information about your setup. This includes where you obtained ProxLB (e.g., as a `.deb` file, from the repository or container image) and also which version you're running in which mode. You can obtain the used version from you image version, your local repository information or by running `proxlb -v`.

Version: 1.0.4
Installed from: (https://repo.gyptazy.com/stable/proxlb_1.0.4_amd64.deb)
Running as: local on Proxmox

**Comment by gyptazy** [comment]
Hey @lgzcoollg,

thanks for reporting this - but unfortunately I can't reproduce this in any way with `dpkg` or `apt-get install`. I just spawned a new buildbox (as LXC) and installed it:  

```
root@buildbox:/tmp# cd /tmp/ && wget https://repo.gyptazy.com/stable/proxlb_1.0.4_amd64.deb && dpkg -i proxlb_1.0.4_amd64.deb
--2024-10-16 07:03:50--  https://repo.gyptazy.com/stable/proxlb_1.0.4_amd64.deb
Resolving repo.gyptazy.com (repo.gyptazy.com)... 77.90.28.33, 2a04:e8c0:18:71d::1337
Connecting to repo.gyptazy.com (repo.gyptazy.com)|77.90.28.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16640 (16K) [application/octet-stream]
Saving to: 'proxlb_1.0.4_amd64.deb.3'

proxlb_1.0.4_amd64.deb.3                                     100%[==============================================================================================================================================>]  16.25K  --.-KB/s    in 0s      

2024-10-16 07:03:50 (145 MB/s) - 'proxlb_1.0.4_amd64.deb.3' saved [16640/16640]

Selecting previously unselected package proxlb.
(Reading database ... 32799 files and directories currently installed.)
Preparing to unpack proxlb_1.0.4_amd64.deb ...
Unpacking proxlb (1.0.4) ...
Setting up proxlb (1.0.4) ...
```

```
root@buildbox:/tmp# apt-get install ./proxlb_1.0.4_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'proxlb' instead of './proxlb_1.0.4_amd64.deb'
The following NEW packages will be installed:
  proxlb
0 upgraded, 1 newly installed, 0 to remove and 58 not upgraded.
Need to get 16.6 kB of archives.
After this operation, 115 kB of additional disk space will be used.
Get:1 https://repo.gyptazy.com/stable  proxlb 1.0.4 [16.6 kB]
Fetched 16.6 kB in 0s (209 kB/s)   
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package proxlb.
(Reading database ... 32799 files and directories currently installed.)
Preparing to unpack .../proxlb_1.0.4_amd64.deb ...
Unpacking proxlb (1.0.4) ...
Setting up proxlb (1.0.4) ...
```

Can you please share some more details?

Thanks,
gyptazy

**Comment by lgzcoollg** [comment]
> Hey @lgzcoollg, 嘿
> 
> thanks for reporting this - but unfortunately I can't reproduce this in any way with `dpkg` or `apt-get install`. I just spawned a new buildbox (as LXC) and installed it:感谢您报告此事 - 但不幸的是，我无法以任何方式使用 or 复制此内容。我刚刚生成了一个新的 buildbox（作为 LXC）并安装了它：
> 
> ```
> root@buildbox:/tmp# cd /tmp/ && wget https://repo.gyptazy.com/stable/proxlb_1.0.4_amd64.deb && dpkg -i proxlb_1.0.4_amd64.deb
> --2024-10-16 07:03:50--  https://repo.gyptazy.com/stable/proxlb_1.0.4_amd64.deb
> Resolving repo.gyptazy.com (repo.gyptazy.com)... 77.90.28.33, 2a04:e8c0:18:71d::1337
> Connecting to repo.gyptazy.com (repo.gyptazy.com)|77.90.28.33|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 16640 (16K) [application/octet-stream]
> Saving to: 'proxlb_1.0.4_amd64.deb.3'
> 
> proxlb_1.0.4_amd64.deb.3                                     100%[==============================================================================================================================================>]  16.25K  --.-KB/s    in 0s      
> 
> 2024-10-16 07:03:50 (145 MB/s) - 'proxlb_1.0.4_amd64.deb.3' saved [16640/16640]
> 
> Selecting previously unselected package proxlb.
> (Reading database ... 32799 files and directories currently installed.)
> Preparing to unpack proxlb_1.0.4_amd64.deb ...
> Unpacking proxlb (1.0.4) ...
> Setting up proxlb (1.0.4) ...
> ```
> 
>  ```
> root@buildbox:/tmp# apt-get install ./proxlb_1.0.4_amd64.deb
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'proxlb' instead of './proxlb_1.0.4_amd64.deb'
> The following NEW packages will be installed:
>   proxlb
> 0 upgraded, 1 newly installed, 0 to remove and 58 not upgraded.
> Need to get 16.6 kB of archives.
> After this operation, 115 kB of additional disk space will be used.
> Get:1 https://repo.gyptazy.com/stable  proxlb 1.0.4 [16.6 kB]
> Fetched 16.6 kB in 0s (209 kB/s)   
> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
> 	LANGUAGE = (unset),
> 	LC_ALL = (unset),
> 	LC_CTYPE = "UTF-8",
> 	LANG = "C"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
> Selecting previously unselected package proxlb.
> (Reading database ... 32799 files and directories currently installed.)
> Preparing to unpack .../proxlb_1.0.4_amd64.deb ...
> Unpacking proxlb (1.0.4) ...
> Setting up proxlb (1.0.4) ...
> ```
> 
> Can you please share some more details?您能否介绍有关情况？
> 
> Thanks, 谢谢 gyptazy 乳糖酶


### Can you please share some more details?

1. EVN: Linux 6.8.12-1-pve
2.  even though have N when in install, its still shown [installed,local] at apt and could be dry-run.
```
root@pve1:~#  apt search proxl
Sorting... Done
Full Text Search... Done
proxlb/now 1.0.4 amd64 [installed,local]
  ProxLB - Rebalance VM workloads across nodes in Proxmox clusters.
```
3. logs:
```
journalctl --no-pager -S  | grep prox
Oct 17 08:58:35 pve1 systemd[1]: Started proxlb.service - ProxLB - Rebalance VM workloads.
Oct 17 08:58:35 pve1 proxlb[944406]:  ProxLB: Error: [config]: Could not find the required options in config file.
Oct 17 08:58:35 pve1 systemd[1]: proxlb.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 17 08:58:35 pve1 systemd[1]: proxlb.service: Failed with result 'exit-code'.
```

**Comment by gyptazy** [comment]
Hey @lgzcoollg,

according to the systemd log this seems to be a different issue?

> Oct 17 08:58:35 pve1 proxlb[944406]:  ProxLB: Error: [config]: Could not find the required options in config file.

Can you share your ProxLB config please?! Please do NOT expose your login credentials and remove them before!

the config changed in a massive way from the structure to version 1.0.3 - so there might be a problem when upgrading from 1.0.2 to 1.0.4.

But I still do not get how you ran your initial issue:
> apt-get install ./proxlb_1.0.4_amd64.deb
N: Download is performed unsandboxed as root as file '/root/proxlb_1.0.4_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

Cheers,
gyptazy

**Comment by lgzcoollg** [comment]
hey there, I found the solved.

cd in the pwd of .deb, and 
`chmod 777 ./`

then install again.
`apt-get install ./proxlb_1.0.4_amd64.deb`
