### ISSUE TITLE
`Bug`: Certain config values that should always be int become bool if value is "0" or "1"

### ISSUE THREAD

**Issue by elliotnev27** [gyptazy/ProxLB#115]
## General
I noticed that when I set "schedule" to "1" I get a long message `<6> ProxLB: Info: [daemon]: Running in daemon mode. Next run in TRUE hours.`

In this particular case, schedule work as intended, but I noticed, storage_balanciness, vm_balanciness, schedule, config_version, might have the same issue. And it could cause unintended behaviors. 

I still need to test this fix, but I believe there would be an easy fix in `__update_config_parser_bools` [d9c133f](https://github.com/elliotnev27/ProxLB/commit/d9c133f7cb19019951d962490e7cfbd0e400279f#diff-4d47e7584181ff92b3c3f57588b89e4fb11158ac22f3d50066588c07267e5a86L296)

## Weighting
Score: 2

## Config
```
[proxmox]
api_host: foo
api_user: foo
api_password: ***
verify_ssl: 0
[vm_balancing]
enable: 1
method: memory
mode: used
type: vm
ignore_nodes: foo1
ignore_vms: foo2
[update_service]
enable: 0
[api]
enable: 0
[service]
demon: 1
schedule: 1
log_verbosity: WARN
config_version:3
```

## Meta
install from .deb in container

Version: 1.0.4
Installed from: deb file
Running as: Container

**Comment by elliotnev27** [comment]
👍 sounds good! I figured as much enjoy the rest of your weekend!

**Comment by gyptazy** [comment]
Hey @elliotnev27,

since 1 hour is an absolutely legitim value and the refactor will take up to Q1 2025 it makes sense to fix this.
Will be part of 1.0.6.

Thanks for reporting!

Cheers,
gyptazy
