### ISSUE TITLE
`Bug`: Proxlb crashes/dies periodically

### ISSUE THREAD

**Issue by bradyloveland** [gyptazy/ProxLB#118]
## General
I have proxlb set to run every 4 hours.  It seems like once a day or two, proxlb will stop running.  I have to manually log into the debian host to start proxlb again.  I haven't seen anything in logs to indicate why it crashes/stops running.

## Weighting
6

## Config
[proxmox]
api_host:
api_user:
api_pass:
verify_ssl: 0
[vm_balancing]
enable: 1
method: memory
mode: used
ignore_nodes: #dummynode01,dummynode02
ignore_vms: #testvm01,testvm02
[storage_balancing]
enable: 0
[update_service]
enable: 1
[api]
enable: 0
[service]
daemon: 1
schedule: 4
log_verbosity: CRITICAL
config_version: 3

## Log
Need help figuring out how to find one

## Meta
installed via wget on debian vm running on proxmox hosts

Version: 1.0.5
Installed from: official wget repository
Running as: debian vm running on proxmox

**Comment by gyptazy** [comment]
Hey @bradyloveland,

can you please attach the proxlb logs? It’s unfortunately very hard to judge a potential issue based on the currently provided information. If it is proxlb related, it should log something like no api connection possible etc. Make sure to set logging to critical and ensure it didn’t get oom killed.

thanks,
gyptazy

**Comment by bradyloveland** [comment]
Can you clarify how to get the logs for Proxlb?  Another thought I had would be to run this on a docker container instead of a VM.  Is it possible to run this in docker using docker compose?

**Comment by gyptazy** [comment]
Hey @bradyloveland,

> Can you clarify how to get the logs for Proxlb? Another thought I had would be to run this on a docker container instead of a VM. Is it possible to run this in docker using docker compose?

Sure, this is described in detail right here in the docs section: https://github.com/gyptazy/ProxLB/blob/main/docs/03_FAQ.md#logging

> Another thought I had would be to run this on a docker container instead of a VM. Is it possible to run this in docker using docker compose?

Sure, just go ahead - also this is documented in a detailed way: https://github.com/gyptazy/ProxLB/tree/main?tab=readme-ov-file#container-quick-start-dockerpodman

You may also simply use the ready to use container (docker) image `cr.gyptazy.com/proxlb/proxlb:latest`.

Cheers,
gyptazy
