### ISSUE TITLE
`Bug`: CLI arg for maintenance mode only works if config arg is not empty

### ISSUE THREAD

**Issue by CartCaved** [gyptazy/ProxLB#119]
## General
When running `proxlb -m <node[,node]>`  the maintenance cli command is ignored if `maintenance_nodes:` in the config is empty.

This is because on line 883 in main (880 in my installed 1.0.5 from repo), the maintenance nodes list is only used if the _config maintenance node list_ length is > 1, instead of checking if the merged maintenance node list length is > 1.

## Fix
Here is the fix (sorry, no proper fork and PR):
```
880c880
<     if len(proxlb_config['vm_maintenance_nodes']) > 1:
---
>     if len(maintenance_nodes_list) > 1:
```

It's easy to work around in the meantime, just add a dummy node to the config - `maintenance_nodes: dummy`

**Comment by gyptazy** [comment]
Hey @CartCaved,

thanks for your bug report and also for directly pointing out the related issue.

Validated and works; added with PR#120 and will be part of release 1.0.6.
Hope it's okay that I mentioned you in the changelog and commit for fixing this.

Cheers,
gyptazy

**Comment by CartCaved** [comment]
Sure, happy to have been helpful - and thanks, it's a great project!
