### ISSUE TITLE
`Feature`: ARM build 

### ISSUE THREAD

**Issue by chodorenko** [gyptazy/ProxLB#124]
## General
Please add ARM release of deb repo, or may be better build packet as noarch

**Comment by gyptazy** [comment]
Hey @chodorenko,

thanks for this suggestion - this is now also included (and also on the CDN https://cdn.gyptazy.com/files/os/debian/proxlb/):

```
# cat Packages | grep -B2 -i arch
Package: proxlb
Version: 1.0.5
Architecture: amd64
--
Package: proxlb
Version: 1.0.5
Architecture: arm64
```

Cheers,
gyptazy
