### ISSUE TITLE
`Feature`: Make logging configurable

### ISSUE THREAD

**Issue by DerbyKurby** [gyptazy/ProxLB#17]
It would be great if the logging could be defined in the config file instead of code editing

**Comment by gyptazy** [comment]
Hey @DerbyKurby,

### Log Verbosity
With the new param `log_verbosity` which can be defined in the config file, the log verbosity can now be defined by using `INFO`, `WARN` or `CRITICAL` (default).

This is currently available in PR #19 and should be merged soon. It will take place with release 1.0.0.

Cheers,
gyptazy

**Comment by DerbyKurby** [comment]
thx
