### ISSUE TITLE
Find best new node for placement for new virtual machines!

### ISSUE THREAD

**Issue by Paul2000DE** [gyptazy/ProxLB#24]
Hello,

I just found this in the Proxmox Matrix channel and works good. But is there also any possibility to get somehow the best node before creating a virtual machine somewhere, so it does not make any rebalance afterwards but before. This would be a good benefit to have.

Thank you!

**Comment by gyptazy** [comment]
Hey @Paul2000DE,

thanks for your feature request and I think this is a great idea!

This (#8) is already on our roadmap for Release 1.1.0. The current idea is to implement an own API interface where you can request this by an http interface. You can find the first ideas in #21. Maybe it might also make sense to have this implemented for cli output. However, I'd like to keep the cli option as slim as possible. Therefore, I really like the API approach. 

What do yo think about this? Would this fit you needs?

Cheers,
gyptazy
