### ISSUE TITLE
`Bug`: Schedule in daemon mode using seconds, not hours

### ISSUE THREAD

**Issue by mater-345** [gyptazy/ProxLB#45]
Hi!

According to the documentation the schedule settings, set the next run in hours:

> > 
> Hours to rebalance in hours. (default: 24)
> 

But it seems the code using this:

        time.sleep(int(schedule) * 60)

With a setting to 1, this will run the checking in 1 minutes rather than 1 hours, as time.sleep using seconds.

**Comment by gyptazy** [comment]
Hey @mater-345,

ouch, thanks for pointing out!
Will be fixed asap!

cheers,
gyptazy
