### ISSUE TITLE
`Feature`: Add a maintenance mode which evacuates all VMs/CTs

### ISSUE THREAD

**Issue by lgzcoollg** [gyptazy/ProxLB#58]
could I ask to add a maintain function for nodes? like ESXi

actually function just: **one click to migrate all VMs from node to others node with balance.** 

any function name could be define by author.

O-) thanks

**Comment by gyptazy** [comment]
Hey @lgzcoollg,

this is already included within the rolling updates feature in https://github.com/gyptazy/ProxLB/pull/48. Before updating the node, all workloads like VMs and CTs will be rebalanced to other nodes. So basically, you simply need an option to this but without rebooting.

I will do this and integrate such an option before merging that PR. This will be the next feature after release 1.0.3. Rolling updates will come with release 1.1.0.

Cheers,
gyptazy

**Comment by gyptazy** [comment]
Hey @lgzcoollg ,

this feature is now included and can be tested from the `main` branch. You can find more about the usage in https://github.com/gyptazy/ProxLB/pull/87.

This feature will be part of the upcoming 1.0.4 release.

Cheers,
gyptazy
