### ISSUE TITLE
Feature: No-op scenario with suggested changes

### ISSUE THREAD

**Issue by daanbosch** [gyptazy/ProxLB#6]
General
I would love a feature where we could get a list off suggested changes. This way we can do it manually to avoid downtime for production critical vm's

Task
- Add no-op option
- Return output in a readable manner

**Comment by gyptazy** [comment]
Hey @daanbosch,

sounds good to me and makes sense. I also already had the idea and the data is already present but I'm wondering how this could be displayed in a human readable way.

For my dev instance it currently provides the following information:

**VMs**
The important thing here are the keys `'node_parent': 'virt01'` and `'node_rebalance': 'virt03'`
```
{'test05': {'cpu_total': 1, 'cpu_used': 0.00318350901213526, 'memory_total': 6341787648, 'memory_used': 442812238, 'disk_total': 12884901888, 'disk_used': 0, 'vmid': 104, 'node_parent': 'virt03', 'node_rebalance': 'virt02'}, 'test06-gyptazy01': {'cpu_total': 1, 'cpu_used': 0.00636832381139609, 'memory_total': 2147483648, 'memory_used': 284038824, 'disk_total': 12884901888, 'disk_used': 0, 'vmid': 105, 'node_parent': 'virt03', 'node_rebalance': 'virt01'}, 'test09-fat01': {'cpu_total': 2, 'cpu_used': 0.00517291368665111, 'memory_total': 6341787648, 'memory_used': 1292982072, 'disk_total': 34359738368, 'disk_used': 0, 'vmid': 110, 'node_parent': 'virt02', 'node_rebalance': 'virt03'}, 'test08-fat01': {'cpu_total': 2, 'cpu_used': 0.0052652871453413, 'memory_total': 6341787648, 'memory_used': 1306799420, 'disk_total': 34359738368, 'disk_used': 0, 'vmid': 107, 'node_parent': 'virt02', 'node_rebalance': 'virt01'}, 'test01': {'cpu_total': 1, 'cpu_used': 0.00332544451284714, 'memory_total': 2147483648, 'memory_used': 320113244, 'disk_total': 12884901888, 'disk_used': 0, 'vmid': 100, 'node_parent': 'virt02', 'node_rebalance': 'virt01'}, 'test07-gyptazy02': {'cpu_total': 1, 'cpu_used': 0.00323307105415694, 'memory_total': 2147483648, 'memory_used': 289626135, 'disk_total': 12884901888, 'disk_used': 0, 'vmid': 106, 'node_parent': 'virt02', 'node_rebalance': 'virt01'}, 'test04': {'cpu_total': 1, 'cpu_used': 0.00331801969704398, 'memory_total': 2147483648, 'memory_used': 285540373, 'disk_total': 12884901888, 'disk_used': 0, 'vmid': 103, 'node_parent': 'virt01', 'node_rebalance': 'virt03'}, 'test03': {'cpu_total': 1, 'cpu_used': 0.00312477270838301, 'memory_total': 2147483648, 'memory_used': 278833252, 'disk_total': 12884901888, 'disk_used': 0, 'vmid': 102, 'node_parent': 'virt01', 'node_rebalance': 'virt03'}}
```

**Nodes**
The information about the expected resources on the nodes after the change:
```
{'virt03': {'cpu_total': 4, 'cpu_used': 0.023274266067178, 'cpu_free': 4, 'memory_total': 8181039104, 'memory_used': 4116291584, 'memory_free': 572100202, 'disk_total': 36638851072, 'disk_used': 2878922752, 'disk_free': 33759928320}, 'virt02': {'cpu_total': 4, 'cpu_used': 0.0268070847295357, 'cpu_free': 4, 'memory_total': 8181039104, 'memory_used': 6356213760, 'memory_free': 65178377, 'disk_total': 36638851072, 'disk_used': 2879078400, 'disk_free': 33759772672}, 'virt01': {'cpu_total': 4, 'cpu_used': 0.0198327359617682, 'cpu_free': 4, 'memory_total': 8181039104, 'memory_used': 1720676352, 'memory_free': 4259921993, 'disk_total': 36638851072, 'disk_used': 3754614784, 'disk_free': 32884236288}}
```

So, let me know what kind of output what be usable and human readable for you. Maybe in a first iteration something like:

VM OLD_NODE NEW_NODE


Cheers,
gyptazy

**Comment by daanbosch** [comment]
Hi gyptazy,

Yes, something like that would definitely work for me. One minor thing, maybe add an arrow so it is clear what the source and target is in a single line:
```VM OLD_NODE -> NEW_NODE```

Love this project :) 
Thanks

**Comment by gyptazy** [comment]
Hey @daanbosch,

added a PR (#13) which adds this functionality:

feature: Add dry-run support to see what kind of rebalancing would be done. [#6]
  * Add new cli param: -d for dry-run: Prints movements to cli
  * Add new cli param: -j for json: Prints movement as a json to cli

Since this was blind coded this is untested, will give it a try in the evening when home and add unit tests. Should be available soon.

**Comment by daanbosch** [comment]
Hi @gyptazy 

That is an awesome addition! One thing that I'm concerned about it though, how to implement these parameters for the docker image. Would it be possible to add these as configuration file options as well?

**Comment by daanbosch** [comment]
I just tested running it with the arguments, and that does indeed work, however it would split where the configuration resides and I need to pass the config file manually in that scenario:
```
❯ docker run -it  --network host -v $(pwd)/test_proxlb.conf:/etc/proxlb/proxlb.conf proxlb -c /etc/proxlb/proxlb.conf -d                                                             
   VM   Current Node   Rebalanced Node
```

I'm not seeing any output though. Can you share how I can enable debugging to see what is going on here? I'm testing on my Proxmox 8 testcluster. I have 3 nodes and created 3 vm's on the first node. The others are empty in this scenario. However there is no recommendation. The non dry-run is not doing anything either. So I guess I'm doing something wrong. This is my config:
```
[balancing]
method: memory
ignore_nodes: dummynode01,dummynode02
ignore_vms: testvm01,testvm02
[service]
daemon: 0
schedule: 24
```

**Comment by daanbosch** [comment]
Regarding those endpoints, that looks like a great starting point.

**Comment by gyptazy** [comment]
Hey @daanbosch,

sorry for that, as written in my PR in #13 that code was written blindly, because I had no access to the environment at that time. Your issue seems to be related to the newly introduced `balanciness` parameter which you can define in your config (default: 10). This one defined the balanciness, when VMs should be rebalanced or when no actions should be performed to avoid re-balancings all the time.

It defines the delta of the percent usage of the chosen resource (memory, disk or cpu) between the node with the highest and lowest resource consumption.

I just pushed an updated version to the PR which should now also provide more feedback on the cli (json return an empty json):

```
# /bin/proxlb -d -c /etc/proxlb/proxlb.conf 
             VM   Current Node   Rebalanced Node
   test08-fat01         virt01            virt02
   test09-fat01         virt01            virt03
   test09-fat03         virt03            virt02
         test01         virt02            virt01
         test05         virt02            virt01
   test09-fat02         virt02            virt01


~# /bin/proxlb -d -c /etc/proxlb/proxlb.conf 
No rebalancing needed according to the defined balanciness.
```

**Comment by daanbosch** [comment]
Hmm I created these vm's:
```
pvesh get /cluster/resources --type vm 
+-----------+------+-------------+---------+-------+--------+---------+-------+--------+----------+-----------+------------+----------------+--------------+
| id        | type | cgroup-mode | content |   cpu |   disk | hastate | level | maxcpu |  maxdisk |    maxmem |        mem | name           | node         |
+===========+======+=============+=========+=======+========+=========+=======+========+==========+===========+============+================+==============+
| qemu/100  | qemu |             |         | 0.03% | 0.00 B |         |       |     10 | 2.20 GiB | 19.58 GiB | 431.65 MiB | testproxlb     | node1 |
+-----------+------+-------------+---------+-------+--------+---------+-------+--------+----------+-----------+------------+----------------+--------------+
| qemu/101  | qemu |             |         | 0.10% | 0.00 B |         |       |      5 | 2.20 GiB | 19.58 GiB | 396.41 MiB | testproxlb2    | node1 |
+-----------+------+-------------+---------+-------+--------+---------+-------+--------+----------+-----------+------------+----------------+--------------+
| qemu/102  | qemu |             |         | 0.05% | 0.00 B |         |       |     12 | 2.20 GiB | 19.58 GiB | 443.69 MiB | testproxlb3    | node1 |
+-----------+------+-------------+---------+-------+--------+---------+-------+--------+----------+-----------+------------+----------------+--------------+
| qemu/9000 | qemu |             |         | 0.00% | 0.00 B |         |       |      1 | 2.20 GiB |  2.00 GiB |     0.00 B | template | node1 |
+-----------+------+-------------+---------+-------+--------+---------+-------+--------+----------+-----------+------------+----------------+--------------+
```

No matter how I tweak the `balanciness` parameter (Tested: 1, 10 ,100) , no changes are suggested to me.

Is it looking at the current CPU/Memory usage or the assigned CPU/Memory? Maybe because they are idle it does not trigger :thinking:

**Comment by gyptazy** [comment]
Pretty interesting, can you edit https://github.com/gyptazy/ProxLB/blob/bf5ba5f8a655a9d3db4cebd3ec5be05022017764/proxlb#L605 and change `CRITICAL` to `INFO` (I will make it configurable soon by the config file) and run `/bin/proxlb -d -c /etc/proxlb/proxlb.conf `?

It should provide you the logged events:
```
~# /bin/proxlb -d -c /etc/proxlb/proxlb.conf 

<6> ProxLB: Info: [logger]: Logger got initialized.
<6> ProxLB: Info: [config]: Using config file: /etc/proxlb/proxlb.conf.
<6> ProxLB: Info: [python-imports]: All required dependencies were imported.
<6> ProxLB: Info: [config]: Configuration file loaded from: /etc/proxlb/proxlb.conf.
<6> ProxLB: Info: [pre-validations]: All pre-validations done.
<6> ProxLB: Info: [config]: Configuration file loaded.
<4> ProxLB: Warning: [api-connection]: API connection does not verify SSL certificate.
<6> ProxLB: Info: [api-connection]: API connection succeeded to host: 10.10.10.211.
<6> ProxLB: Info: [node-statistics]: Added node virt02.
<6> ProxLB: Info: [node-statistics]: Added node virt01.
<6> ProxLB: Info: [node-statistics]: Added node virt03.
<6> ProxLB: Info: [node-statistics]: Created node statistics.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test09-fat02.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test05.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test01.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test08-fat01.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test09-fat01.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test02.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [api-get-vm-include-exclude-tags]: Got PLB include group.
<6> ProxLB: Info: [vm-statistics]: Added vm test06-gyptazy01.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test04.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [api-get-vm-include-exclude-tags]: Got PLB include group.
<6> ProxLB: Info: [vm-statistics]: Added vm test07-gyptazy02.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test09-fat03.
<6> ProxLB: Info: [api-get-vm-tags]: Got VM comment from API.
<6> ProxLB: Info: [vm-statistics]: Added vm test03.
<6> ProxLB: Info: [vm-statistics]: Created VM statistics.
<6> ProxLB: Info: [balancing-method-validation]]: Valid balancing method: memory
<6> ProxLB: Info: [balanciness-validation]]: Rebalancing is for memory is not needed.
<6> ProxLB: Info: [rebalancing-tags-group-include]: Create include groups of VM hosts.
<6> ProxLB: Info: [rebalancing-resource-statistics-update]: Updated VM and node statistics.
<6> ProxLB: Info: [rebalancing-tags-group-exclude]: Create exclude groups of VM hosts.
<6> ProxLB: Info: [rebalancing-calculator]: Balancing calculations done.
<6> ProxLB: Info: [rebalancing-executor]: Starting dry-run to rebalance vms to their new nodes.
<6> ProxLB: Info: [rebalancing-executor]: No rebalancing needed according to the defined balanciness.
No rebalancing needed according to the defined balanciness.
<6> ProxLB: Info: [post-validations]: All post-validations succeeded.
<6> ProxLB: Info: [daemon]: Not running in daemon mode. Quitting.
```

**Comment by gyptazy** [comment]
That is strange, especially when all VMs are currently running on node1.

ProxLB uses the currently really used resources of the VMs, takes the most consuming VM, takes the node with the max free resources, assigns them to that node and repeats this. It just spawned up a new cluster with three nodes and placed some VMs there and couldn't reproduce this.

Can you add in the line https://github.com/gyptazy/ProxLB/blob/bf5ba5f8a655a9d3db4cebd3ec5be05022017764/proxlb#L624
the following `print(node_statistics_rebalanced)` (take care of the indention) and provide the output please? Are you also running LXC on those nodes or other things?

Thanks

**Comment by daanbosch** [comment]
> ProxLB uses the currently really used resources of the VMs,

Hmm yeah that would explain why the test vm's are not moved, they are not doing anything. Does it makes sense to make it possible to balance based on the assigned resources? As some services can burst and use more at any given moment.

**Comment by daanbosch** [comment]
>  Are you also running LXC on those nodes or other things?
No, there are no lxc's

**Comment by gyptazy** [comment]
> > ProxLB uses the currently really used resources of the VMs,
> 
> Hmm yeah that would explain why the test vm's are not moved, they are not doing anything. Does it makes sense to make it possible to balance based on the assigned resources? As some services can burst and use more at any given moment.

Hm, maybe I can integrate this by a trigger but IMHO it doesn't make much sense because you want to move them by the actual usage (periodically) to ensure an always up to date balanced cluster. Of course, it should be validated that the possible maximum usage of all VMs can not exceed the node's memory but moving them by potential usage would more or less simply in-balance the cluster.

If there's really a need for, I can probably integrate this.

**Comment by daanbosch** [comment]
Okay, looks like we can then close this one as the intended purpose is working as expected. It was an interpretation error on my side. Yes I will open a feature request. Thank you

**Comment by gyptazy** [comment]
Feature got merged and is available in head, now. This feature will be part of Release 1.0.0.
