### ISSUE TITLE
Bug? Error? With Conf File

### ISSUE THREAD

**Issue by Dulux-Oz** [gyptazy/ProxLB#69]
Using the example configuration from the ProxLB Documentation (with the server and root password changed, obviously), when I run `proxlb -c /etc/proxlb/proxlb.conf` I get:

`<2> ProxLB: Error: [config]: Could not find the required options in config file.`

When I put in *every* option listed in the ProxLB documentation, I get the same error.

The permissions on the proxlb.conf file are 644, owner plb:plb

What am I doing wrong? :smile:

Cheers

Dulux-Oz

**Comment by gyptazy** [comment]
Hey @Dulux-Oz,

that depends on your version. You should always use the corresponding config version according to  your binary. When using the deb packages or the repository version up to 1.2 (including 1.2), they’re all the same. The new config schema is introduced with the current development version. So, if you’re currently using the version from the main branch, it’s already 1.0.3b and requires the new layout and options.

so, which version are you using or how did you install it? Then I can tell you which format is needed :)

just in addition, this issue does not exist with the stable packages.

cheers,
gyptazy

**Comment by Dulux-Oz** [comment]
[Grumble Grumble GitHub not relaying me emails Grumble Grumble]

Hi @gyptazy,

I installed ProxLB from Debian Repo you provided (ie `deb https://repo.gyptazy.ch/ /`) - I *think* this was/is 1.2.

Also, using the conf example you provide (above) and changing the relevant user, etc, I still get the same error.

Any ideas?

Cheers

Dulux-Oz

**Comment by gyptazy** [comment]
Hey @Dulux-Oz,

the referenced config is for version 1.3 and does not work with versions below that one. Please use a config related to your version. 1.0-1.2 can be mixed: https://github.com/gyptazy/ProxLB/blob/v1.0.0/proxlb.conf

Cheers,
gyptazy

**Comment by Dulux-Oz** [comment]
Hi @gyptazy,

Thanks for getting back to me.

So I basically used the example conf file you referenced (with the proper api_hosts, etc) and got back the following (which is progress, as its now a different error :grin: ):

```
<6> ProxLB: Info: [logger]: Logger verbosity got updated to: DEBUG.
<7> ProxLB: Starting new HTTPS connection (1): pven1,pven2,pven3:8006
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1045, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x73e4136f9e90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pven1,pven2,pven3', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x73e4136f9e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/proxlb", line 219, in api_connect
    api_object = proxmoxer.ProxmoxAPI(proxmox_api_host, user=proxmox_api_user, password=proxmox_api_pass, verify_ssl=proxmox_api_ssl_v)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 154, in __init__
    self._backend = importlib.import_module('.backends.%s' % backend, 'proxmoxer').Backend(host, service=service, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/backends/https.py", line 243, in __init__
    self.auth = ProxmoxHTTPAuth(self.base_url, user, password, otp, verify_ssl, timeout, service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/backends/https.py", line 72, in __init__
    self._getNewTokens(password=password, otp=otp)
  File "/usr/lib/python3/dist-packages/proxmoxer/backends/https.py", line 84, in _getNewTokens
    response_data = requests.post(self.base_url + "/access/ticket",
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pven1,pven2,pven3', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x73e4136f9e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/proxlb", line 833, in <module>
    main()
  File "/usr/bin/proxlb", line 811, in main
    api_object = api_connect(proxmox_api_host, proxmox_api_user, proxmox_api_pass, proxmox_api_ssl_v)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/proxlb", line 220, in api_connect
    except urllib3.exceptions.NameResolutionError:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.exceptions' has no attribute 'NameResolutionError'
```

**Comment by gyptazy** [comment]
Hey @Dulux-Oz ,

it's a little bit hard to judge the things without seeing the config file, but the error is, that it cannot resolve the hostname to the Proxmox server.

Seeing `HTTPSConnectionPool(host='pven1,pven2,pven3'` this, lets me assume that you have defined all three nodes as the hosts (this is a feature of the upcoming version 1.3 and not included in older versions). With < 1.3 please only use a single hostname or IP. Please do not mix configs and features between the versions. The release of 1.3 is stated as a minor release but provides huge improvements in usability which made me need to switch to a different config layout. 

Please also make sure that your feature is already available in a used version. You can find all of them in the changeling directory: https://github.com/gyptazy/ProxLB/tree/main/.changelogs

I plan to release 1.3 soon and then this should be streamlined.

Cheers,
gyptazy

**Comment by Dulux-Oz** [comment]
Hi @gyptazy,

OK, thanks for the help. I think it'll be best to wait until v1.3 is released before spending any more brain power on this - I'll look forward to the new version.

Thanks again for the help, and for the plug-in - I really appreciate both  :smile: 

Cheers

Dulux-Oz

**Comment by gyptazy** [comment]
Hey @Dulux-Oz,

you're welcome and sorry for this confusing things here.

What you can also do:
* Grab the 1.3beta source from the current main branch
  * https://raw.githubusercontent.com/gyptazy/ProxLB/main/proxlb
* Use the upper config (https://github.com/gyptazy/ProxLB/issues/69#issuecomment-2322860769) provided in this issue for 1.3

Then you're already good to go :)

Cheers,
gyptazy
