### ISSUE TITLE
Config File issue?

### ISSUE THREAD

**Issue by michaelahess** [gyptazy/ProxLB#73]
I'm on 1.02 and receive this:

Sep 10 11:18:51 proxmox-srv0-n1 systemd[1]: Started proxlb.service - ProxLB - Rebalance VM workloads.
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:  ProxLB: Info: [logger]: Logger verbosity got updated to: INFO.
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:  ProxLB: Warning: [api-connection]: API connection does not verify SSL certificate.
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:  ProxLB: Info: [api-connection]: API connection succeeded to host: localhost.
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:  ProxLB: Info: [only-on-master-executor]: No master only rebalancing is defined. Skipping validation.
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]: Traceback (most recent call last):
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:   File "/usr/bin/proxlb", line 933, in <module>
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:     main()
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:   File "/usr/bin/proxlb", line 914, in main
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:     node_statistics = get_node_statistics(api_object, ignore_nodes)
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:   File "/usr/bin/proxlb", line 297, in get_node_statistics
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:     ignore_nodes_list =  ignore_nodes.split(',')
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]:                          ^^^^^^^^^^^^^^^^^^
Sep 10 11:18:51 proxmox-srv0-n1 proxlb[15021]: AttributeError: 'NoneType' object has no attribute 'split'
Sep 10 11:18:51 proxmox-srv0-n1 systemd[1]: proxlb.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 11:18:51 proxmox-srv0-n1 systemd[1]: proxlb.service: Failed with result 'exit-code'.

Config file looks like this:

[proxmox]
api_host: localhost
api_user: root@pam
api_pass: mypassword
verify_ssl: 0
[balancing]
enable: 1
method: memory
mode: used
master_only: 0
# ignore_nodes: dummynode01,dummynode02
# ignore_vms: testvm01,testvm02
[service]
daemon: 1
schedule: 24
log_verbosity: INFO
# [update_service]
# enable: 0
# [storage_balancing]
# enable: 0
# [api]
# enable: 0

I've tried without master_only as well. I've done this on three hosts all with the same results.

**Comment by gyptazy** [comment]
Hey @michaelahess,

thanks for reporting! This is already fixed with #71 (https://github.com/gyptazy/ProxLB/blob/main/.changelogs/1.0.3/71_fix_ignore_vm_node_handling_if_unset.yml) and part of the upcoming 1.0.3 release. Until the new stable release is present, you can simply keep the `ignore_nodes` and `ignore_vms` lines with any dummy content.

Release 1.0.3 is to be expected at the 2024-09-12 (see also: https://github.com/gyptazy/ProxLB/issues/72).

Hope it helps.

Cheers,
gyptazy
