### ISSUE TITLE
cdn repo down

### ISSUE THREAD

**Issue by includes08** [gyptazy/ProxLB#80]
Hi,

It looks like your cdn repo is not working for me.

https://cdn.gyptazy.ch/files/amd64/debian/proxlb/proxlb_1.0.3_amd64.deb

**Submitted URL:**
https://cdn.gyptazy.ch/files/amd64/debian/proxlb/proxlb_1.0.3_amd64.deb
**Report Finished:**
Sep 20, 2024, 21:15:49
**Error:**
DNS resolution failed

**Comment by gyptazy** [comment]
Hey @includes08,

thanks for the information and that's right :)

I'm taking the weekend time to restructure all my services. This currently also affects my website, etc.
Should be back by the beginning of the week :)

Cheers,
gyptazy

**Comment by includes08** [comment]
> Hey @includes08,
> 
> thanks for the information and that's right :)
> 
> I'm taking the weekend time to restructure all my services. This currently also affects my website, etc. Should be back by the beginning of the week :)
> 
> Cheers, gyptazy

Would it be possible to upload .deb to file.io or something similar :x?
Just so i can hobby around 😄

**Comment by gyptazy** [comment]
> Would it be possible to upload .deb to file.io or something similar :x? Just so i can hobby around 😄

You can find the new location at https://cdn.gyptazy.com/files/os/debian/proxlb/

**Comment by includes08** [comment]
You too!
