### ISSUE TITLE
Unable to resolve cdn.gyptazy.ch

### ISSUE THREAD

**Issue by bradyloveland** [gyptazy/ProxLB#81]
Hello,

This looks like a great project!  Unfortunately, I'm unable to get any resolution for cdn.gyptazy.ch.  Is this url still live for repository or wget?

**Comment by gyptazy** [comment]
Hey @bradyloveland,

thanks for your message. I’m currently creating a new infrastructure for my personal services and also changed from a country specific domain to a global one. It probably takes up to the end until everything is finished but you can find the latest proxlb package here: https://cdn.gyptazy.com/files/os/debian/proxlb/proxlb_1.0.3_amd64.deb

Cheers,
gyptazy

**Comment by bradyloveland** [comment]
Amazing, I was able to get it installed and running, but I have one more question - on the UI version, can you clarify how the pve-proxmolb-service-ui gets installed?  Is that something I would install via apt install, or do I need to download the deb file from your repository as well?

**Comment by gyptazy** [comment]
Hey @bradyloveland,

the UI integration is temporary not available. There's also another issue - the current details and reasons are explained in #44. I hope to find a better way to provide a UI integration quickly again.

PS: All packages with the UI integration have been removed for safety reasons.

Cheers,
gyptazy

**Comment by bradyloveland** [comment]
Got it, thanks!

**Comment by gyptazy** [comment]
Documentation has been updated.
