### ISSUE TITLE
Unable to pull Docker image

### ISSUE THREAD

**Issue by JonahMMay** [gyptazy/ProxLB#85]
Command: `docker create --name proxlb cr.gyptazy.com/proxlb/proxlb:latest`

Response: `Error response from daemon: Get "https://cr.gyptazy.com/v2/": tls: failed to verify certificate: x509: certificate is valid for gyptazy.com, www.gyptazy.com, not cr.gyptazy.com
`

**Comment by gyptazy** [comment]
Hey @JonahMMay 

thanks for reporting, this is right. The Container Reg is currently not available and gets shifted to a new node.

This may take up to tomorrow. If it’s urgent, you can still create an image from source.

cheers,
gyptazy

**Comment by gyptazy** [comment]
Hey @JonahMMay,

as promised it's now available again:

```
% skopeo inspect docker://cr.gyptazy.com/proxlb/proxlb:latest | head -n 17
{
    "Name": "cr.gyptazy.com/proxlb/proxlb",
    "Digest": "sha256:40217abb48c664128deba9f58b22cd208c6cf52baa95a31020043a7b48a28f3b",
    "RepoTags": [
        "v1.0.3",
        "latest"
    ],
    "Created": "2024-10-04T09:30:23.786055416Z",
    "DockerVersion": "",
    "Labels": {
        "maintainer": "gyptazy@gyptazy.com",
        "org.label-schema.description": "ProxLB - Rebalance VM workloads across nodes in a Proxmox cluster.",
        "org.label-schema.schema-version": "0.9",
        "org.label-schema.url": "https://github.com/gyptazy/ProxLB"
    },
    "Architecture": "amd64",
    "Os": "linux",
```

Cheers,
gyptazy
