### ISSUE TITLE
Crashes on dry run when generating node update statistics, only if CTs are included

### ISSUE THREAD

**Issue by K3CAN** [gyptazy/ProxLB#88]
I'm getting this error if I include containers via `type: all` or `type: ct` during a dry-run.   
With INFO logs, I get the usual vm-statistics, then when it goes to create the node-update-statistics, the CPU over-provision error stacks a few times, then it dies.

It works fine if I only run for VMs. 

```
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 102%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 152%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 177%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 227%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 277%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 327%.

Traceback (most recent call last):
  File "/usr/bin/proxlb", line 1505, in <module>
    main()
  File "/usr/bin/proxlb", line 1479, in main
    node_statistics    = update_node_statistics(node_statistics, vm_statistics)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/proxlb", line 659, in update_node_statistics
    node_statistics[vm_value['node_parent']]['cpu_assigned']            = node_statistics[vm_value['node_parent']]['cpu_assigned'] + int(vm_value['cpu_total'])
                                                                          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'pve2'
```

And my config (minus api info): 

```
[vm_balancing]
enable: 1
method: memory
mode: used
type: ct
ignore_nodes: pve2
balanciness: 10
[storage_balancing]
enable: 0
[update_service]
enable: 0
[api]
enable: 0
[service]
daemon: 0
schedule: 24
log_verbosity: INFO
config_version: 3
 
```

Since the dry-run fails, I haven't tried a live run.

**Comment by gyptazy** [comment]
Hey @K3CAN,

thanks for reporting, that's a bug in the `ignore_nodes` handling.

Will fix is asap.

Cheers,
gyptazy

**Comment by gyptazy** [comment]
Hey @K3CAN,

which version are you currently running? Can you try if this still applies with version 1.0.4b which is in the current `main` branch? Can't reproduce it there but see a reason why it might fail in recent versions when using `ignore_nodes`.

Cheers

**Comment by K3CAN** [comment]
Looks like I was on the current stable release, 1.0.3.   
I just updated to 1.0.4.1 and that seems to have solved the issue!


There's still some odd looking warnings in the logs, though:
```
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 103%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 153%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 203%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 253%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 278%.
<4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 328%.
```
Also
```
<6> ProxLB: Info: [balancing-method-validation]: Valid balancing method: memory
<6> ProxLB: Info: [balancing-mode-validation]: Valid balancing method: used
<6> ProxLB: Info: [balanciness-validation]: Rebalancing for memory is needed. Highest usage: 67% | Lowest usage: 44%.
```
Followed later by
```
<6> ProxLB: Info: [cli-output-generator-dry-run]: Starting dry-run to rebalance vms to their new nodes.
<6> ProxLB: Info: [cli-output-generator-dry-run]: No rebalancing needed.
```
I don't know that any of that is actually an issue, though. It might be that I'm just not understanding what the logs are telling me. 

The over-provision percentage showing 6 different values is a little confusing, and I'm not clear whether or not it has determined that a re-balance is necessary.  It seems to initially find that it needs to re-balance, but then decide later in the process that it doesn't...

**Comment by gyptazy** [comment]
Hey @K3CAN,

> Looks like I was on the current stable release, 1.0.3. I just updated to 1.0.4.1 and that seems to have solved the issue!

Great news, happy to see it working for you now.

> There's still some odd looking warnings in the logs, though:
> ```
> <4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 103%.
> <4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 153%.
> <4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 203%.
> <4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 253%.
> <4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 278%.
> <4> ProxLB: Warning: [node-update-statistics]: Node pve3 is overprovisioned for CPU by 328%.
> ```

That's ok and representing the current values of each iteration.

> 
> Also
> 
> ```
> <6> ProxLB: Info: [balancing-method-validation]: Valid balancing method: memory
> <6> ProxLB: Info: [balancing-mode-validation]: Valid balancing method: used
> <6> ProxLB: Info: [balanciness-validation]: Rebalancing for memory is needed. Highest usage: 67% | Lowest usage: 44%.
> ```
> ```
> <6> ProxLB: Info: [cli-output-generator-dry-run]: Starting dry-run to rebalance vms to their new nodes.
> <6> ProxLB: Info: [cli-output-generator-dry-run]: No rebalancing needed.
> ```


> The over-provision percentage showing 6 different values is a little confusing, and I'm not clear whether or not it has determined that a re-balance is necessary. It seems to initially find that it needs to re-balance, but then decide later in the process that it doesn't...

That's right. Whatever the outcome is - no rebalancing will occur in dry-run mode. Maybe I should adjust the log message to make it more clearly (I thought the prefix `dry-run` would already be enough). The different values are representing each iteration of calculation (possible VM movement).

Thanks for your help to make ProxLB better!
gyptazy
